### ISSUE TITLE
Is MOV r0, r0 expected in thumb arithmetic.asm

### ISSUE THREAD

**Issue by ghost** [jsmolka/gba-suite#11]
Hey,

In https://github.com/jsmolka/gba-tests/blob/master/thumb/arithmetic.asm, on line 128, is the (trivial?) instruction "mov r0, r0" instruction expected ? 

Is the instruction a typo i.e., should it be "mov r0, 0" (or something like it) to make more sense in the context of the test ?

Thanks,
Revanth

**Comment by jsmolka** [comment]
It's just a way to set r0 to 0xFFFF'FFFF.

```
mov     r0, 0  ; r0 = 0
mvn     r0, r0  ; r0 = ~r0
```

Then we add 1, wich causes an overflow and sets the carry.

**Comment by ghost** [comment]
Thanks for the explanation @jsmolka.

**Comment by ghost** [comment]
Hi @jsmolka ,

Just FYI - I've added an acknowledgement and link to your repo from my project here. [ZAP Project Link](https://github.com/krevanth/ZAP)

See Section 5 in the README.

Thanks,
Revanth
