### ISSUE TITLE
Add tests for STMDB/STMIB with empty Rlist

### ISSUE THREAD

**Issue by Ankeraout** [jsmolka/gba-suite#2]
Expected results (tested on real hardware):
- **[stmdb_empty_rlist.asm](https://github.com/jsmolka/gba-suite/files/4105074/stmdb_empty_rlist.txt):** blue (R15 is stored at Rn-40h)
- **[stmib_empty_rlist.asm](https://github.com/jsmolka/gba-suite/files/4105080/stmib_empty_rlist.txt):** green (R15 is stored at Rn+4)

**Comment by jsmolka** [comment]
@Ankeraout I think these [tests](https://github.com/jsmolka/gba-suite/blob/a3807af14c028d96f00da1a35374bf7ce56e2b8b/arm/block_transfer.asm#L215) already cover empty rlists in block transfer.

**Comment by Ankeraout** [comment]
They cover STMIA and LDMIA but not STMDB and STMIB.
We've discovered that at least 2 emulators (NanoboyAdvance and AmazinglyAdvanced) failed these 2 tests, while passing gba-suite's ARM test.

**Comment by jsmolka** [comment]
My emulator fails them aswell. I'll take a look at it during the weekend and add them to the test suite.

**Comment by jsmolka** [comment]
@Ankeraout I fixed the issue and added an additional test. Here is a short summary:

- stmda stores the pc at [rn - 0x3C]
- stmdb stores the pc at [rn - 0x40]
- stmia stores the pc at [rn + 0x00]
- stmib stores the pc at [rn + 0x04]

I'll take a look at the loads with empty rlist now and see if I missed something there.
