### ISSUE TITLE
Tests removed in earlier commit still present in .gba

### ISSUE THREAD

**Issue by Arignir** [jsmolka/gba-suite#9]
Hi, 

I've been trying your Thumb test suite lately, and (at least) the test 170 and 171 removed in [this commit](https://github.com/jsmolka/gba-suite/commit/880b943f98c9122dbab5c729b52d087343e27953#diff-8a1cc5aa8ca8eccfab1b90590d4392f188d25a47622686dea2cc3002986aa357) are still present in the `thumb.gba` file provided with the source code.

Thank you for your attention,
Arignir

**Comment by jsmolka** [comment]
I doubt that. The binary doesn't change when reassembling.

**Comment by Arignir** [comment]
Hmm I may have downloaded an earlier version by inadvertence. I can't re-download if from master right now and check that so I'll trust your judgement.
